### PR TITLE
#66 Fix error message on user rejecting request

### LINKED ISSUE #66: error when the wallet rejects a deploy is crazy
Screenshot 2024-10-02 at 14 41 21

### PR DESCRIPTION
**Pull request by hardingjam**
## Motivation

Error message is too long on user rejecting metamask request

## Solution

Add a more semantic error message
closes #66 

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs

### CODE REVIEW

**Comment by hardingjam** [comment]
image

File: app/_components/SubmissionModal.tsx [hunk 1]
```diff
@@ -290,7 +290,10 @@ export const SubmissionModal = ({
 					}`
 				);
 			} else {
-				setError(e?.cause?.message || e?.message || 'An error occurred');
+				if (e.message.includes('User rejected the request')) {
+					return setError('User rejected the transaction.');
+				}
+				setError('An error occurred');
```
Comment (thedavidmeister) [inline app/_components/SubmissionModal.tsx:296]: this isn't a useful error though, we still need the error rmessage to be available somehow

**Review by thedavidmeister — CHANGES_REQUESTED** [review]

File: app/_components/SubmissionModal.tsx (hunk 1 above)
Comment (hardingjam) [reply app/_components/SubmissionModal.tsx:296]: Do we put the full error message in a dropdown?

Comment (hardingjam) [reply app/_components/SubmissionModal.tsx:292]: Using error.details instead of a custom error returning eg:

image

Comment (thedavidmeister) [reply app/_components/SubmissionModal.tsx:292]: ok, let's include the details here too

**Review by thedavidmeister — DISMISSED** [review]

**Review by hardyjosh — APPROVED** [review]
